version: "3"

services:

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=b3test
      - POSTGRES_DB=b3_test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=b3_test
      - MYSQL_USER=b3test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
